version: '2'

services:
  httplogger:
    image: 'golang:1.6'
    expose:
      - '8080'
    ports:
      - '80:8080'
    volumes:
      - './:/go/src/github.com/paduraru/httpLogger'
    entrypoint: 'go run /go/src/github.com/paduraru/httpLogger/main.go'